<template><div class="demo-workflow"><el-alert v-if="!enabled" title="当前不是演示模式" description="为保护真实系统，本页面只在独立 DEMO 服务中启用；READ_ONLY 和 CONTROLLED_EXECUTION 均不能在此执行。" type="warning" show-icon/><div class="panel"><div class="panel-head"><div><h3>受控执行演示</h3><p>操作员发起 → dry-run → 独立审批 → 备份 → 执行 → 验证 → 必要时回滚</p></div><span class="mode-badge">{{zhStatus(session.mode)}}</span></div><div class="demo-actions"><el-button type="primary" :disabled="!enabled" @click="prepare('cleanup')">准备日志清理成功场景</el-button><el-button type="danger" :disabled="!enabled" @click="prepare('rollback')">准备验证失败回滚场景</el-button><el-button @click="verifyAudit">校验审计链</el-button></div></div>
<div class="demo-grid"><div class="panel"><h3>1. 操作员预检</h3><div class="demo-state"><b>{{stageText}}</b><span>{{scenarioText}}</span></div><pre>{{previewText}}</pre></div><div class="panel"><h3>2. 独立人工审批</h3><p>审批员必须与发起人不同。凭据只在本页内存中短暂使用。</p><el-input v-model="approver.username" placeholder="审批员用户名"/><el-input v-model="approver.password" type="password" show-password placeholder="审批员密码"/><el-button type="success" :disabled="stage!=='WAITING_APPROVAL'" @click="approve">审批并签发一次性令牌</el-button></div><div class="panel"><h3>3. 执行与验证</h3><el-button class="task-primary" type="primary" :disabled="stage!=='APPROVED'" @click="execute">执行受控操作</el-button><div v-if="result" class="result-card"><span class="state-chip" :class="result.status==='ROLLED_BACK'?'warning':''">{{zhStatus(result.status)}}</span><p>备份：{{result.backup_ref?'已创建':'不适用'}}</p><p>验证：{{result.verification}}</p><p v-if="result.rollback_status">回滚：{{zhStatus(result.rollback_status)}}</p></div></div><div class="panel"><h3>4. 审计完整性</h3><div class="health-row"><span>哈希链</span><b class="state-chip" :class="auditValid===false?'warning':''">{{auditValid===null?'尚未校验':auditValid?'完整有效':'校验失败'}}</b></div><p>页面只展示结构化决策链和公开结果，不展示模型隐藏思维。</p></div></div><el-alert v-if="error" :title="error" type="error" show-icon/></div></template>
<script setup lang="ts">
import{computed,reactive,ref}from"vue";import{api,apiAs}from"../api";import{useSession}from"../stores/session";import{zhStatus}from"../status";
interface Reset{log_candidate_id:string;config_candidate_id:string;is_demo:boolean}interface Approval{id:string}interface Token{access_token:string}interface Decision{approval_token:string}interface Execution{status:string;backup_ref:string|null;verification:string;rollback_status:string|null}
const session=useSession(),enabled=computed(()=>session.mode==="DEMO"),stage=ref("IDLE"),scenario=ref<"cleanup"|"rollback">("cleanup"),preview=ref<Record<string,unknown>>(),approvalId=ref(""),taskId=ref(""),approvalToken=ref(""),approverToken=ref(""),argumentsValue=ref<Record<string,unknown>>({}),result=ref<Execution>(),auditValid=ref<boolean|null>(null),error=ref("");const approver=reactive({username:"",password:""});const stageText=computed(()=>({IDLE:"等待选择场景",WAITING_APPROVAL:"dry-run 通过，等待审批",APPROVED:"审批通过，等待执行",DONE:"执行闭环完成"}[stage.value]||stage.value));const scenarioText=computed(()=>scenario.value==="cleanup"?"安全日志清理":"配置验证失败自动回滚");const previewText=computed(()=>preview.value?JSON.stringify(preview.value,null,2):"尚未执行 dry-run");
async function prepare(kind:"cleanup"|"rollback"){error.value="";result.value=undefined;scenario.value=kind;try{const reset=await api<Reset>("/demo/reset",{method:"POST"});argumentsValue.value=kind==="cleanup"?{candidate_id:reset.log_candidate_id}:{candidate_id:reset.config_candidate_id,content:"server { listen 9090; }\n"};const tool=kind==="cleanup"?"safe_log_cleanup":"config_safe_update";preview.value=await api("/executions/dry-run",{method:"POST",body:JSON.stringify({tool_name:tool,arguments:argumentsValue.value})});const task=await api<{id:string}>("/tasks",{method:"POST",body:JSON.stringify({goal:`DEMO ${scenarioText.value}`,requested_mode:"DEMO"})});taskId.value=task.id;const approval=await api<Approval>(`/tasks/${task.id}/approvals`,{method:"POST",body:JSON.stringify({tool_name:tool,arguments:argumentsValue.value})});approvalId.value=approval.id;stage.value="WAITING_APPROVAL"}catch(e){error.value=e instanceof Error?e.message:"场景准备失败"}}
async function approve(){error.value="";try{const login=await apiAs<Token>("/auth/login",null,{method:"POST",body:JSON.stringify(approver)});approver.password="";approverToken.value=login.access_token;await apiAs(`/approvals/${approvalId.value}/approve`,login.access_token,{method:"POST",body:JSON.stringify({reason:"演示资源、影响范围、备份和回滚方案已人工复核"})});const claimed=await api<Decision>(`/approvals/${approvalId.value}/claim`,{method:"POST"});approvalToken.value=claimed.approval_token;stage.value="APPROVED"}catch(e){approver.password="";error.value=e instanceof Error?e.message:"审批失败"}}
async function execute(){error.value="";try{const tool=scenario.value==="cleanup"?"safe_log_cleanup":"config_safe_update";result.value=await api<Execution>("/executions/run",{method:"POST",body:JSON.stringify({task_id:taskId.value,tool_name:tool,arguments:argumentsValue.value,approval_token:approvalToken.value,...(scenario.value==="rollback"?{fault:"verification"}:{})})});approvalToken.value="";stage.value="DONE";await verifyAudit()}catch(e){approvalToken.value="";error.value=e instanceof Error?e.message:"执行失败"}}
async function verifyAudit(){try{const value=approverToken.value?await apiAs<{valid:boolean}>("/audit/verify",approverToken.value):await api<{valid:boolean}>("/audit/verify");auditValid.value=value.valid}catch(e){error.value=e instanceof Error?e.message:"审计校验失败"}}
</script>
