<template><div class="panel"><div class="panel-head"><div><h3>{{title}}</h3><p>{{descriptions[kind]}}</p></div><el-button @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="warning" show-icon/>
<div v-if="kind==='inspections'" class="action-row"><el-button type="primary" @click="runInspection">立即巡检</el-button><span>定时巡检由服务端受信任配置控制。</span></div>
<el-form v-if="kind==='drift'" class="action-form" label-position="top"><el-form-item label="配置标识"><el-input v-model="form.path_ref"/></el-form-item><el-form-item label="配置内容（敏感行自动脱敏）"><el-input v-model="form.content" type="textarea" :rows="5"/></el-form-item><el-button type="primary" @click="baseline">建立基线</el-button><el-button @click="drift">检测漂移</el-button></el-form>
<el-form v-if="kind==='knowledge'" class="action-form" label-position="top"><el-form-item label="检索"><el-input v-model="query" @keyup.enter="load"/></el-form-item><el-form-item label="文档编号"><el-input v-model="form.document_id"/></el-form-item><el-form-item label="标题"><el-input v-model="form.title"/></el-form-item><el-form-item label="内容"><el-input v-model="form.content" type="textarea" :rows="4"/></el-form-item><el-button type="primary" @click="addKnowledge">添加待审核知识</el-button></el-form>
<el-form v-if="kind==='settings'" class="action-form" label-position="top"><el-form-item label="快照间隔（秒）"><el-input-number v-model="settings.snapshot_interval_seconds" :min="30" :max="86400"/></el-form-item><el-form-item label="保留天数"><el-input-number v-model="settings.retention_days" :min="1" :max="365"/></el-form-item><el-button type="primary" @click="saveSettings">保存设置</el-button></el-form>
<div v-if="kind==='audit'" class="action-row"><el-button type="primary" @click="verifyAudit">验证哈希链</el-button><el-button @click="exportAudit">导出审计记录</el-button><span>{{result}}</span></div>
<el-table v-if="rows.length" :data="rows"><el-table-column v-for="key in keys" :key="key" :label="labels[key]||key"><template #default="scope">{{format(scope.row[key])}}</template></el-table-column><el-table-column v-if="kind==='incidents'" label="操作" width="190"><template #default="scope"><el-button size="small" @click="incident(scope.row.id,'ACKNOWLEDGED')">确认</el-button><el-button size="small" type="success" @click="incident(scope.row.id,'RESOLVED')">解决</el-button></template></el-table-column><el-table-column v-if="kind==='knowledge'" label="审核" width="180"><template #default="scope"><el-button size="small" type="success" @click="review(scope.row.document_id,'APPROVED')">通过</el-button><el-button size="small" type="danger" @click="review(scope.row.document_id,'REJECTED')">拒绝</el-button></template></el-table-column></el-table><el-empty v-else-if="kind!=='settings'" description="当前没有记录"/><pre v-if="raw">{{raw}}</pre></div></template>
<script setup lang="ts">
import{computed,onMounted,reactive,ref,watch}from"vue";import{useRoute}from"vue-router";import{api}from"../api";import{zhStatus}from"../status";
type Row=Record<string,any>;const route=useRoute(),kind=computed(()=>String(route.meta.kind)),title=computed(()=>String(route.meta.title));
const descriptions:Record<string,string>={inspections:"采集快照与安全基线，异常由确定性规则生成事件。",incidents:"跟踪巡检产生的故障和安全事件。",drift:"建立脱敏基线并比较当前配置。",knowledge:"未审核知识不能支持高风险执行。",audit:"查询、验证并导出防篡改审计链。",settings:"管理非秘密参数，密钥只能通过环境变量注入。"};
const endpoints:Record<string,string>={inspections:"/inspections",incidents:"/incidents",drift:"/config-drift",knowledge:"/knowledge",audit:"/audit/events",settings:"/settings"};const labels:Record<string,string>={id:"编号",document_id:"文档编号",title:"标题",summary:"摘要",severity:"级别",status:"状态",path_ref:"配置标识",created_at:"时间",captured_at:"采集时间",event_type:"事件类型"};
const rows=ref<Row[]>([]),raw=ref(""),error=ref(""),result=ref(""),query=ref("Linux"),form=reactive({path_ref:"",document_id:"",title:"",content:""}),settings=reactive({snapshot_interval_seconds:300,retention_days:30});const keys=computed(()=>rows.value.length?Object.keys(rows.value[0]).filter(k=>!["payload","previous_hash","current_hash"].includes(k)).slice(0,6):[]);
function format(v:unknown){if(typeof v==="boolean")return v?"是":"否";if(v==null)return"—";return zhStatus(v)}async function load(){error.value="";try{const suffix=kind.value==="knowledge"?`?query=${encodeURIComponent(query.value)}`:"",data=await api<any>(endpoints[kind.value]+suffix);if(kind.value==="settings")Object.assign(settings,data);else if(Array.isArray(data))rows.value=data;else raw.value=JSON.stringify(data,null,2)}catch(e){error.value=e instanceof Error?e.message:"加载失败"}}
async function act(fn:()=>Promise<void>){try{await fn();await load()}catch(e){error.value=e instanceof Error?e.message:"操作失败"}}const post=(p:string,b?:unknown)=>api(p,{method:"POST",body:b?JSON.stringify(b):undefined}),put=(p:string,b:unknown)=>api(p,{method:"PUT",body:JSON.stringify(b)});const runInspection=()=>act(async()=>{await post("/inspections/run")}),baseline=()=>act(async()=>{await post("/config-drift/baselines",{path_ref:form.path_ref,content:form.content})}),drift=()=>act(async()=>{raw.value=JSON.stringify(await post("/config-drift/check",{path_ref:form.path_ref,current_content:form.content}),null,2)}),addKnowledge=()=>act(async()=>{await post("/knowledge",{document_id:form.document_id,title:form.title,content:form.content,review_status:"PENDING"})}),review=(id:string,status:string)=>act(async()=>{await put(`/knowledge/${id}`,{review_status:status})}),incident=(id:string,status:string)=>act(async()=>{await put(`/incidents/${id}`,{status})}),saveSettings=()=>act(async()=>{await put("/settings",settings)}),verifyAudit=()=>act(async()=>{result.value=JSON.stringify(await api("/audit/verify"))});async function exportAudit(){await act(async()=>{const data=await api("/audit/export"),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)])),a=document.createElement("a");a.href=url;a.download="麒麟智维盾-审计记录.json";a.click();URL.revokeObjectURL(url)})}
onMounted(load);watch(kind,load);
</script>
